import jsPDF from 'jspdf';

const PAGE_HEIGHT = 297;   // A4 mm
const MARGIN_TOP = 15;
const MARGIN_BOTTOM = 20;
const LEFT = 10;
const BODY_WIDTH = 190;    // 210mm A4 minus margins

export function generateSummaryPDF(analysis: any, fileName: string = 'MedSight_Summary.pdf') {
  const doc = new jsPDF();
  let y = MARGIN_TOP;

  /** Advance the cursor, starting a new page when we run out of room. */
  const space = (needed: number) => {
    if (y + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
      doc.addPage();
      y = MARGIN_TOP;
    }
  };

  /** Write text that wraps to BODY_WIDTH and paginates as needed. */
  const write = (text: string, { size = 11, indent = 0, gap = 5.5 } = {}) => {
    doc.setFontSize(size);
    const lines: string[] = doc.splitTextToSize(text, BODY_WIDTH - indent);
    lines.forEach((line) => {
      space(gap);
      doc.text(line, LEFT + indent, y);
      y += gap;
    });
  };

  const heading = (text: string) => {
    y += 4;
    space(9);
    write(text, { size: 14, gap: 7 });
  };

  const section = (title: string, items: string[]) => {
    heading(title);
    if (items.length === 0) {
      write('None recorded in this report.', { indent: 2 });
      return;
    }
    items.forEach((item) => write(`- ${item}`, { indent: 2 }));
  };

  write('MedSight Summary', { size: 18, gap: 9 });
  write(`Patient: ${analysis.patientName || 'Not stated'}`, { size: 12, gap: 6 });
  write(`Report Date: ${analysis.reportDate || 'Not stated'}`, { size: 12, gap: 6 });
  write(`Report Type: ${analysis.reportType || 'Not stated'}`, { size: 12, gap: 6 });

  section(
    'Key Findings:',
    (analysis.keyFindings ?? []).map((f: any) => f.description).filter(Boolean)
  );
  section(
    'Test Results:',
    (analysis.testResults ?? []).map(
      (t: any) => `${t.testName}: ${t.result} (Ref: ${t.referenceRange})`
    )
  );
  section(
    'Medications:',
    (analysis.medications ?? []).map(
      (m: any) => `${m.name} (${m.dosage}): ${m.purpose}`
    )
  );
  section('Questions for Doctor:', analysis.questions ?? []);

  heading('Summary:');
  write(analysis.summary || 'No summary available.', { indent: 2 });

  y += 6;
  write(
    'Disclaimer: This summary was generated by AI from an uploaded medical report. It may contain errors and is not a diagnosis. Always confirm findings with a qualified clinician.',
    { size: 9, gap: 4.5 }
  );

  doc.save(fileName);
}
